project:
  type: website
  output-dir: docs

website:
  title: "Data Stories by Richi Susil Jacob"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/richisusiljacob
      - href: index.qmd
        text: Blog
format:
  html:
    theme: slate
    css: styles.css



